name: BuildTest

on: [push, pull_request]

jobs:
  test:
    strategy:
      matrix:
        go-version: [1.13.x, 1.14.x, 1.15.x, 1.16.x]
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go-version }}
      - name: Check out code
        uses: actions/checkout@v2
      - name: Setup CI
        run: make setup_ci && git stash
      - name: Build
        run: go build -mod=readonly ./...
      - name: Verify
        run: go mod verify
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
      - name: Test code
        uses: magefile/mage-action@v1
        with:
          version: latest
          args: go:test